# Generated by Django 4.0.6 on 2022-08-13 22:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
